server:
  port: 9090

spring:
  application:
    name: demo01

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true&autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=CTT
    username: root
    password: 123456

  cloud:
    sentinel:
      transport:
        dashboard: localhost:8080

nacos:
  discovery:
    server-addr: 127.0.0.1:8848
  config:
    server-addr: 127.0.0.1:8848

logging:
  level:
    com.demo01: debug